apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-responder-webhook
    receivers:
      - uid: cp-incident-responder
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST
          maxAlerts: 10

policies:
  - orgId: 1
    receiver: incident-responder-webhook
    group_by: ['alertname', 'route', 'endpoint']
    group_wait: 1s
    group_interval: 2s
    repeat_interval: 1m
    routes:
      - receiver: incident-responder-webhook
        object_matchers:
          - ['alertname', '=', 'OrderTracker5xxResponses']
